/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servidor.DTO.AnteproyectoDTO;
import servidor.DTO.EvaluadoresDTO;
import servidor.sop_rmi.ClsGestionAnteproyectos;
import servidor.sop_rmi.GestionAnteproyectosInt;

/**
 *
 * @author USERPC
 */
public class ClsBuscarAnteproyecto extends javax.swing.JFrame {

    /**
     * Creates new form ClsBuscarAnteproyecto
     */
    private  GestionAnteproyectosInt objRemoto ;
    
    public ClsBuscarAnteproyecto(GestionAnteproyectosInt objRemoto) throws RemoteException {
        initComponents();
        this.objRemoto = objRemoto;
        llenarComboBox5();
    }
     public void llenarComboBox5() throws RemoteException {        
        ArrayList<AnteproyectoDTO> listaAnteproyectos = this.objRemoto.listarAnteproyectos();
        for (int i = 0; i < listaAnteproyectos.size(); i++) {
            
            jComboBox1.addItem(Integer.toString(listaAnteproyectos.get(i).getCodigo()));
            
        }
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("CÓDIGO ANTEPROYECTO");

        jLabel1.setText("BUSCAR ANTEPROYECTO");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("ATRÁS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/img/encabezado.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int codigo = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        AnteproyectoDTO objAnteproyecto = null;
        EvaluadoresDTO objEvaluador = null;
        try {
            objAnteproyecto = objRemoto.buscarAnteproyecto(codigo);
            objEvaluador = objRemoto.buscarEvaluador(codigo);
            
        } catch (RemoteException ex) {
            Logger.getLogger(ClsBuscarAnteproyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (objAnteproyecto == null) {
            JOptionPane.showMessageDialog(null, "El anteproyecto no existe");
        }else {
            
            limpiarArea();
//            String nombreColumnas [] = {"codigo","titulo","estudiante_1","estudiante_2","director", "concepto", "estado", "evaluador_1", "Evaluador_2"};
//             String data[][] =  new String[1][9];
//            data[0][0] = Integer.toString(objAnteproyecto.getCodigo());
//            data[0][1] = objAnteproyecto.getTitulo();
//            data[0][2] = objAnteproyecto.getEstudiante_1();
//            data[0][3] = objAnteproyecto.getEstudiante_2();
//            data[0][4] = objAnteproyecto.getDirector();
//             if (objAnteproyecto.getConcepto() == 1) {
//                data[0][5] = "Aprobado";
//            }else if (objAnteproyecto.getConcepto() == 2) {
//                data[0][5] = "No Aprobado";
//            }
//             if (objAnteproyecto.getEstado() == 1) {
//                data[0][6] = "Sin Asignacion";
//            }else if (objAnteproyecto.getEstado() == 2) {
//                data[0][6] = "Evaluadores Asignados";
//            }else if (objAnteproyecto.getEstado() == 3) {
//                data[0][6] = "En Revisión";
//            }else if (objAnteproyecto.getEstado() == 4) {
//                data[0][6] = "Revisado";
//            }
//            
//             if (objEvaluador == 
//            null) {
//                data[0][7] = "Sin Evaluador";
//                data[0][8] = "Sin Evaluador";
//            }else {
//                data[0][7] = objEvaluador.getEvaluador_1();
//                data[0][8] = objEvaluador.getEvaluador_2();
//              
//            }
//            jTable1.setModel(new DefaultTableModel(data, nombreColumnas));
            
            
            jTextArea1.append("Codigo: "+Integer.toString(objAnteproyecto.getCodigo()));
            jTextArea1.append(System.getProperty("line.separator"));
            jTextArea1.append("Título: "+objAnteproyecto.getTitulo());
            jTextArea1.append(System.getProperty("line.separator"));
            jTextArea1.append("Estudiante 1: "+objAnteproyecto.getEstudiante_1());
            jTextArea1.append(System.getProperty("line.separator"));
            jTextArea1.append("Estudiante 2: "+objAnteproyecto.getEstudiante_2());
            jTextArea1.append(System.getProperty("line.separator"));
            jTextArea1.append("Director: "+objAnteproyecto.getDirector());
            jTextArea1.append(System.getProperty("line.separator"));
            if (objAnteproyecto.getConcepto() == 1) {
                jTextArea1.append("concepto: Aprobado");
            }else if (objAnteproyecto.getConcepto() == 2) {
                jTextArea1.append("concepto: No Aprobado");
            }
            jTextArea1.append(System.getProperty("line.separator"));
            if (objAnteproyecto.getEstado() == 1) {
                jTextArea1.append("Estado: Sin asignación");
            }else if (objAnteproyecto.getEstado() == 2) {
                jTextArea1.append("Estado: Evaluadores asignados");
            }else if (objAnteproyecto.getEstado() == 3) {
                jTextArea1.append("Estado: En revisión");
            }else if (objAnteproyecto.getEstado() == 4) {
                jTextArea1.append("Estado: Revisado");
            }
            jTextArea1.append(System.getProperty("line.separator"));
            if (objEvaluador == null) {
                jTextArea1.append("evaluador 1: Sin evaluador");
                jTextArea1.append(System.getProperty("line.separator"));
                jTextArea1.append("evaluador 2: Sin evaluador");
                jTextArea1.append(System.getProperty("line.separator"));
            }else {
                jTextArea1.append("evaluador 1: "+objEvaluador.getEvaluador_1());
                jTextArea1.append(System.getProperty("line.separator"));
                jTextArea1.append("evaluador 2: "+objEvaluador.getEvaluador_2());
                jTextArea1.append(System.getProperty("line.separator"));
            }
            
            JOptionPane.showMessageDialog(null, "Anteproyecto encontrado");
       }
//     
    }//GEN-LAST:event_jButton1ActionPerformed
    public void limpiarArea(){
        jTextArea1.setText("");
    }
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
